### ISSUE TITLE
Pages "Installer" & "My Packages" are broken after update ethchain to 2.18

### ISSUE THREAD

**Issue by uniconstructor** [dappnode/DNP_ETHCHAIN#61]
Steps to reproduce:

1) Click on Update button in message
2) Click "update" on ethchain package.
3) Wait for install
4) Go to "My packages": 

![Снимок экрана от 2020-01-01 02-34-41](https://user-images.githubusercontent.com/1384545/71636379-f7ca1800-2c3f-11ea-9264-8210e973c774.png)

Error log from UI:
<details><summary>(expand)</summary>

```
sagas.ts:81 Check core update
start.ts:28 CONNECTED to 
url: ws://my.wamp.dnp.dappnode.eth:8080/ws 
realm: dappnode_admin
sagas.js:20 Error on requestChainData: Error: no callee registered for procedure <requestChainData.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:20
sagas.js:83 Error fetching userActionLogs:  Error: no callee registered for procedure <getUserActionLogs.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:83
sagas.js:19 Error on fetch DappnodeParams: Error: no callee registered for procedure <getParams.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:19
sagas.js:19 Error on fetch DappnodeStats: Error: no callee registered for procedure <getStats.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:19
sagas.js:19 Error on fetch DappnodeDiagnose: Error: no callee registered for procedure <diagnose.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:19
sagas.ts:80 Error on pingDappnodeDnps/dappmanager: Error: no callee registered for procedure <ping.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.ts:80
sagas.ts:96 Error on getDnpsVersionData/dappmanager: Error: no callee registered for procedure <getVersionData.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.ts:96
sagas.js:19 Error on fetch WifiStatus: Error: no callee registered for procedure <logPackage.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:19
sagas.js:19 Error on fetch PasswordIsInsecure: Error: no callee registered for procedure <passwordIsSecure.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:19
sagas.js:19 Error on fetch AutoUpdateData: Error: no callee registered for procedure <autoUpdateDataGet.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:19
sagas.js:19 Error on fetch Identity: Error: no callee registered for procedure <seedPhraseGetPublicKey.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:19
wrapRoute.ts:80 Error on listPackages.dappmanager.dnp.dappnode.eth: Error: no callee registered for procedure <listPackages.dappmanager.dnp.dappnode.eth>
    at wrapRoute.ts:64
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ wrapRoute.ts:80
sagas.js:40 Error on fetchNotifications: Error: no callee registered for procedure <notificationsGet.dappmanager.dnp.dappnode.eth>
    at index.js:91
    at makePromise.js:865
    at N (makePromise.js:822)
    at k.when (makePromise.js:637)
    at g.run (makePromise.js:493)
    at t._drain (Scheduler.js:68)
    at drain (Scheduler.js:28)
    at MutationObserver.<anonymous> (env.js:79)
(anonymous) @ sagas.js:40
```

</details>

**Comment by vdo** [comment]
@uniconstructor  Looks like DAPPMANAGER was not properly initialized when this happened. Can you still reproduce? If so, can you paste the docker logs of the package `DAppNodeCore-dappmanager.dnp.dappnode.eth` ? 
Also, refresh browser cache first

**Comment by uniconstructor** [comment]
@vdo, cannot reproduce this right now, because I am need to reinstall my system from scratch. System crashed when I am accidentaly downgrade my system instead of upgrade.

I have to finish my server hardware upgrade first, then I will take an another try: new server, new system. 

I am closing this issue for now and will reopen it if a problem will happen again.
